### ISSUE TITLE
0.29.2 breaks webpack build

### ISSUE THREAD

**Issue by m-mohr** [commonmark/commonmark.js#195]
Since 0.29.2 I'm getting the following error when building a Vue component that uses commonmark.js:
> "export 'default' (imported as 'commonmark') was not found in 'commonmark'

Im importing with `import commonmark from 'commonmark';`.

I'm building with vue-cli and that uses webpack again. I suspect that #186 broke it, at least I can make it work by downgrading to 0.29.1.

**Comment by m-mohr** [comment]
Fixed it by using babel's "transpileDependencies". Nevertheless it's not nice that things break in patch versions.

**Comment by m-mohr** [comment]
Do I now need to use `import { commonmark } from 'commonmark';` instead of `import commonmark from 'commonmark';`?

**Comment by jgm** [comment]
See the discussion in #136.

I'm sorry about this; I don't use JavaScript myself and I'm not up on the module technology.  As far as I could tell, #136 was doing the right thing, but maybe not.  It may work to do `import * as commonmark from 'commonmark'`, as suggested in the discussion there. But it may be that we are doing things in a non-standard way that violates expectations (and creates problems with backwards-compatibility). IN that case, I'd like to fix it, but I'll need help from people who know what they're doing with JS modules.

**Comment by m-mohr** [comment]
Thank you, I'm also not really into all the details about JS modules. 

I guess it would help to add to the readme how to include the library. I guess most people would try `import commonmark from 'commonmark'` instead of `import * as commonmark from 'commonmark'`. For me it seems that the default export is missing and should be added.

**Comment by jgm** [comment]
Sure.  How do I fix it so that `import commonmark from 'commonmark'` works again?
And, will that break `import * as commonmark from 'commonmark'`?

**Comment by m-mohr** [comment]
Again, I'm not an expert and haven't checked it, but I'd assume something like that should work:

```js
import Node from "./node.js"
import Parser from "./blocks.js";
import Renderer from "./render/renderer.js";
import HtmlRenderer from "./render/html.js";
import XmlRenderer from "./render/xml.js";

const lib = { Node, Parser, Renderer, HtmlRenderer, XmlRenderer };
export lib; // makes `import * as commonmark from 'commonmark'` work
export default lib; // makes `import commonmark from 'commonmark'` work
```

But better let others experts double check that this works.

**Comment by HP4k1h5** [comment]
not an expert but this is my understanding as well, at least for node 14.11+

> export lib; // makes `import * as commonmark from 'commonmark'` work
> export default lib;

this export setup should provide the two import styles, as well as 

```javascript
import { lib } from './lib.js' // same as import * as lib from './lib.js'
```

**Comment by jgm** [comment]
So, is this the normal thing to do, making both styles of import work?

**Comment by m-mohr** [comment]
No, usually I'd only expect the export default thing that allows me to do `import commonmark from 'commonmark'`. I've not seen many libraries do `import * as commonmark from 'commonmark'`. Anyway, 0.29.2 introduced it and some people adopted, so to not break things again now it seems it must support both?!

**Comment by jgm** [comment]
For some reason `export lib` didn't work.  I had to use a constant there instead.
But I've adopted this suggestion.

I'm not sure about whether to continue supporting `import * as commonmark`, but we should probably at least support it in the next release, with a deprecation notice.

**Comment by jgm** [comment]
OK, having both styles seems to be a problem:
https://github.com/commonmark/commonmark.js/runs/1166893414?check_suite_focus=true
I think I'll just go to the preferred style and people will have to deal with the breakage.
Fortunately 0.29.2 was very recently released, so I hope it won't affect too many people.

**Comment by jgm** [comment]
Actually, I'm going to reopen this and try to get more feedback.
I see that some libraries use one style (e.g. `entities`), while others use the other.
I'm not sure what is best, but supporting both seems to be impossible.
Advice welcome from people who know more about this than I do!

**Comment by jgm** [comment]
I've reverted the changes related to this issue, for now.

**Comment by jgm** [comment]
This should be fixed by #203

**Comment by MartinX3** [comment]
I'm still getting `"export 'default' (imported as 'commonmark') was not found in 'commonmark'` with 0.29.3
Or I understand the PR wrong
